### ISSUE TITLE
Proposal to add our song to the playlist

### ISSUE THREAD

**Issue by ejupriv** [David-Lor/HurdyGurdy-Rock-Metal-Spotify-Playlist#13]
All,
I would like to propose our song "Lost Places" to your playlist in which hurdy gurdy is also featured. Much appreciated:

https://open.spotify.com/track/4Olpm3jmjVax4cmR4LMPc7?si=30a5f4ff6b614faf

Thank you, Eric (from Cantorca)

**Comment by David-Lor** [comment]
Hello Eric, thanks for the heads up! It's been added to the playlist (: 
Regards!
